version: "3.9"
services:
  arangodb:
    image: arangodb:3.9.7
    environment:
      ARANGO_ROOT_PASSWORD: quizzer
    ports:
      - 8529:8529
    volumes:
      - ./arangodb/volumeData:/var/lib/arangodb3
  quizzer-view:
    build:
      context: python
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    
